language: generic
before_install:
- npm install -g gitbook-cli
- rm -rf _build
- echo TRAVIS_SECURE_ENV_VARS = ${TRAVIS_SECURE_ENV_VARS}
install:
- gitbook install
- gitbook build
script:
- git checkout --orphan gh-pages
- git rm --cached -r .
- git clean -df
- rm -rf *~
- echo "*~" > .gitignore
- echo "_book" >> .gitignore
- echo "node_modules" >> .gitignore
- git add .gitignore
- git commit -m "Ignore some files"
- cp -r _book/* .
- git add .
- git commit -m "Publish book"
- git push --force --quiet "https://${GITHUB_TOKEN}@${GH_REF}" gh-pages:gh-pages
branches:
  only:
  - master
env:
  global:
  - GH_REF: github.com/breezetemple/how-to-use-gitbook.git
  - secure: MWhXSsy6Si9LZ5oVp/eUAQHF9Lfac+oB8CoiHo0mnwlCb595gbgrmtyPkUzhH4wKR9GCY2SA7hUV/sCl2fuRO3+mjzT1yStrkQ6jH/MGRjjRZ+9uOxNyTv5PjCb8h7EIyA99vjUyDW+fyIWuiXEL5J8rxTmyP2gQ48/3AVSXjNRia/NcyE/hJ2kTIj7vWWrf+Rpw0NGeCMt1ooCqZS5Y6vt4/eGD0q/5/NLjuaYmO8G3SVw9ny2CyGlUwz+Gttr6eUTIOms/ywMawt4wJOorWcsaef5slztXeTRzYN2daSyS+GBQd168OuVxE+ZCxg2JX8tKE54hBQZMaIpmXABV3b24lnTsxk0yMz2Rhj/bHdFHmofNMvqx2m8hoA5Ym+BVjzhj/bC2WxRkomDw+WHvFrCu9Qx4vJr1sJSevrIaEXb8fttOXU80/pYJUmrypzi8a+acDh4v+Lrdmt0ZMNjUlNBsKvADG/M72bIuYpHKWThL2f3RNyM8AjWFpC4McfsCbrD3pO4P6k1vHNmTrXBaJd6OhvmBXxnEN6YAV1B9zP35rdP0BYPbUuWLt8daEr7CHw/L5+Cxh/0L4bl/O/rxPpWRh6djV7cO5eEx9+lBJpwAjJ8IFsDgj6Pu7TbIt2JsEKYwzQlgqgtLNNxSuGlx8SqVLCZbFLEbB1B0Yi0KlsQ=
  - secure: gNjwMbwrG8VBvYHzVDq+niYAB38YpX5bMi1VXeXYiIqAsuB65R/SYuegUHsJhqyF9CFItHz/+nLArMt/A+U4Ok6kUP+ve7wKV/FFsY3IVfgl9IJUqPA/iarckVj6/FbtJdNaC6bH4bhNEMX7czdtjzONxR/UgOIC31HhOvgoxkib7qi1HEOAMQkIQy0o2LdkyaL0uB077chw/2o3n8Ltgox+xSU7LaASIpwtaSY4xWPsU7VNt1W1OcbHUk1lGs9+CMHeok3OHbh3VkUtBrNvQBeZ6Ik24UMY4CFaQdlztxU/EksiDmsP1YQZch/e8tQVH+ghBdStFDq7YprwLwbMxIUU0AQP/g/FWyPvmEFEVmixrhaD4SB0Iww+snqLYAOkZ1D0jACUbAEemz/Azday7XaDgErJeiQXJoD4TSNgGuIR+tG7JJAFk39qYG4oq7Qe3RqXC3mn4ybsGmgNPpkznSMtUq6WZDaitqlHqD4dgf+5sTzFvqDG9HP9i7U3KL0pzRwYe5yHROyRAPSYo7c4ACt9WjygTeYvray0MFWleNfuirbQ9U8djn7kuUTW+ZOaYq/90iJ6wMikeTvIZgeU+xBxo9Q9zVSH9NVVrans3i/HbqaX76qDBlIkr0CuAbs6oM2pbfVcS7O0ZgGIhELs5jwtJpZOnZtFpimEkiRMzJI=
