language: generic
before_install:
- npm install -g gitbook-cli
- rm -rf _build
- echo TRAVIS_SECURE_ENV_VARS = ${TRAVIS_SECURE_ENV_VARS}
install:
- gitbook install
- gitbook build
script:
- git checkout --orphan gh-pages
- git rm --cached -r .
- git clean -df
- rm -rf *~
- echo "*~" > .gitignore
- echo "_book" >> .gitignore
- echo "node_modules" >> .gitignore
- git add .gitignore
- git commit -m "Ignore some files"
- cp -r _book/* .
- git add .
- git commit -m "Publish book"
- git push --force --quiet "https://${GITHUB_TOKEN}@${GH_REF}" gh-pages:gh-pages
branches:
  only:
  - master
env:
  global:
  - GH_REF: github.com/breezetemple/how-to-use-gitbook.git
  matrix:
    secure: eIaoSsStZ8YE1abVsIAHybTz7ILozLjSgtVNgNF9ZY5YitndciCVO9b6efIIi2yM/2iOpNRZNgyNnsgdxrAyPQdXD+QRpdQn25IjrMafJ0aFGENfoJW4F1pBsRSUtwolzDYWW8hMUP+U4+dPPsy9IyO06Kkb7WnjvmucII39QPpQL7ASlKTcZOK1BvHSz4MYgTi7IOCSmdNcjRsLuzeQOdSiSq/J1PbNM84IUjmtxUirpCT2m2yM3Krq8L1i2cDQ37ZI1ZrKOl4imWoCksNYbNkoJuTdJoswKbN3ONhGjc41Wx8HdE/oK3EdV2zUhdKEuEd079vTDxTtPVF4KP5Wm4eW0XXVynW9n92VYOVZlYxqUt1pyKL8ey/rN6UmV2dySIlMJmq1Cw/mlYnVo6vlEZWOPbINBIJFQr3OIsziXd4ApQQ24tguW89/NDw0epxH5AM02nZ8giV0dS0s5cabYWsqJDUoo9sCrgNrOieBxJIPo0YAteyfNiwRzosUB8Q5dxMzi++4HXvDymtY1eZUpocfSC1UGzyaBHS/EzL7NL2pTGPfiHlcrqvXETOXgCax21UbN27/yUhMVNbwrmVbjQv4BvBmesguOvOpA9kuuzjv4nYavkJo8hhNqWdpJvkVtvk9KWha4R/vaj1C7k7cESMbpcUd2dl5wXz+FSLo/pg=
