language: node_js
node_js: stable
before_install:
    - npm install -g gitbook-cli
install:
    - gitbook install
    - gitbook build
test: true
script:
    - git checkout --orphan gh-pages
    - git rm --cached -r .
    - git clean -df
    - rm -rf *~
    - cp -r _book/* .
    - git add .
    - git commit -m "Publish book"
    - git push -f "https://${GITHUB_TOKEN}@${GH_REF}" master:gh-pages

deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  on:
    branch: master
env:
  global:
    - GH_REF: github.com/breezetemple/how-to-use-gitbook.git
