language: generic
before_install:
- npm install -g gitbook-cli
- rm -rf _build
- composer config --global github-oauth.github.com "$GITHUB_TOKEN"
- echo TRAVIS_SECURE_ENV_VARS = ${TRAVIS_SECURE_ENV_VARS}
install:
- gitbook install
- gitbook build
script:
- git checkout --orphan gh-pages
- git rm --cached -r .
- git clean -df
- rm -rf *~
- echo "*~" > .gitignore
- echo "_book" >> .gitignore
- echo "node_modules" >> .gitignore
- git add .gitignore
- git commit -m "Ignore some files"
- cp -r _book/* .
- git add .
- git commit -m "Publish book"
- git push --force --quiet "https://${GITHUB_TOKEN}@${GH_REF}" gh-pages:gh-pages
branches:
  only:
  - master
env:
  global:
  - GH_REF: github.com/breezetemple/how-to-use-gitbook.git
  - secure: yJDmp+6kktp1HF+HYWcyv90hWEigO3B+7dmaSbrYnHtMYVloDLOFc2SWv6cr6ODY6zk35zJiK9hl2FWbjtYDQVJzgZrHScOHiySwT/UKTpoD1ULAtc2CYk7C3qI5Oc6oK5rE2IAWBqV7JhAUip5GWZlULACcF4gTOTtTzhOymKwaNBSXqwk+vHeWVaG2gQjzEOCy7v9lOwgYKYWSxRK5uqLPYVnp8WZlrUwVviqSUCfwZ6iPtDx1hIFkcGkUCtXOYI7ZpMjWwkjmJQH/BgTLNPVY9Za4HEnV4bl1xqJ4/2M29H/EBwhU3z4FYB+jxoV63eT/yLYuRrPO+um0Z3S1fK13rN3LgKnOBimwmr/OnyRs6X4cs6oON1GbGwDlI7+vfusI1NT1W/VDCf8oV40va4fJT56qKSj6pIFn4HWo+kJO/gsjV/OcCdU7F9y/FQZGz5lFxI91wXD7HG04dZ2YO816mdRaAr6k71m9pa/Y6Gl80lxYEtMNTIiYgzqUMhKQNG67mQOZah9NGuq9JvJLb5aTe6EMoX2N4qsf207uLxkJBjRBfhfYOvkrmJU0l774RHbLXe9QFmWg/yIVA7VblxUcUgBV0uDImitwXbXpztZls8e5YGDMLTL0x8/ckUyVAm2xH2gHzXoKitAotl5F81BJUd+BTPx+0jAEkG9Tcag=
