language: generic
before_install:
- npm install -g gitbook-cli
install:
- gitbook install
- gitbook build
deploy:
  provider: pages
  local_dir: _book
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
env:
  global:
  - GH_REF: github.com/breezetemple/how-to-use-gitbook.git
